name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: node:lts
      env:
        REDIS_HOST: redis
    services:
      redis:
        image: redis
        ports:
          - "6379:6379"
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: npm ci
      - name: Bootstrap monorepo packages
        run: |
          npm run bootstrap
          npm run build
      - name: Lint
        run: npm run lint
      - name: Test monorepo packages
        run: npm test
