name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - "6379:6379"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install npm packages
        run: npm ci
      - name: Bootstrap monorepo packages
        run: |
          npm run bootstrap
          npm run build
      - name: Lint
        run: npm run lint
      - name: Test monorepo packages
        run: npm test
